settings = {
    "source_path": "Domande.xlsx",
    "destination_path": "./",
    "tmp_destination_path": "./tmp",
    "template_path": "./template",
    "template_name": "template.xlsx",
    "file_name": "exam",
    "zip_name": "generated.zip",
    "subject": ["SISTEMI E RETI"],
    "classroom": [3, 4, 5],
    "document_title": "Compito di Sistemi e Reti - A.S. 2023/2024 - Classe 3F",
    "document_header": "Cognome e Nome: ___________________________________________",
    "number_of_exams": 5,
    "number_of_questions": 49,
    "number_of_options": 4,
    "number_on_document": False,
    "number_on_questions": False,
    "shuffle_questions": True,
    "shuffle_options": True,
    "export_solutions": True,
    "single_inclusion": False,
    "export_to_pdf": False,
    "include_to_zip": False, 
    "supported_excel_formats": [".xlsx", ".xls"],
    "supported_table_formats": [".csv"],
    "subject_denomination": "MATERIA",
    "classroom_denomination": "CLASSE",
    "include_denomination": "INCLUDERE",
    "question_denomination": "DOMANDA",
    "solution_denomination": "CORRETTA",
    "option_denomination": "OPZIONE",
    "include_accept_denomination": "SI"
}