config = {
    "source_path": "Domande.xlsx",
    "destination_path": "$HOME/Desktop",
    "tmp_destination_path": "./tmp",
    "template_path": "./template",
    "template_name": "template.xlsx",
    "file_name": "esame",
    "zip_name": "Esami",
    "subject": ["SISTEMI E RETI"],
    "classroom": [3],
    "sector": ["INGRESSO"],
    "document_title": "Test di Ingresso di Sistemi e Reti - A.S. 2024/2025 - Classe 3F",
    "document_header": "Cognome e Nome: ___________________________________________",
    "number_of_exams": 4,
    "number_of_questions": 40,
    "number_of_options": 4,
    "number_on_document": False,
    "number_on_questions": False,
    "shuffle_questions": True,
    "shuffle_options": True,
    "export_solutions": True,
    "single_inclusion": False,
    "export_to_pdf": False,
    "include_to_zip": True, 
    "supported_excel_formats": [".xlsx", ".xls"],
    "supported_table_formats": [".csv"],
    "subject_denomination": "MATERIA",
    "classroom_denomination": "CLASSE",
    "sector_denomination": "SETTORE",
    "include_denomination": "INCLUDERE",
    "question_denomination": "DOMANDA",
    "solution_denomination": "CORRETTA",
    "option_denomination": "OPZIONE",
    "include_accept_denomination": "SI"
}